### ISSUE TITLE
Multi-line SOQL Query Fails

### ISSUE THREAD

**Issue by Varout** [jsmithdev/soqe#4]
When writing a multi-line query such as
```
SELECT Count(Id), Account.Id FROM Contact 
WHERE Account.Id != null 
GROUP BY Account.Id
```
instead of in a single line, an error is thrown as the new lines are replaced as a string length 0.  When spaces are added to the end of the lines, the query works correctly.

Would suggest changing the `''` in
https://github.com/jsmithdev/soqe/blob/047253621b657de4fe6b978418f74011004cef06/extension.js#L62 to replace with a space instead.

**Comment by jsmithdev** [comment]
thanks @Varout worked out here. added, did audit and published version 0.1.1 so should update soon. thanks again.
